team_data ={
    "Administration" : "Base",
    "Authentication" : "Kuvempu",
    "Azure":"Verdi",
    "BackupRestore": "Base",
    "Base" : "Base",
    "BaseSystem" : "Base",
    "CAA_SSLTLS_Scan_Test": "Kuvempu",
    "CentralManagement":"CM",
    "Certificate": "Base",
    "ComponentTestSuite" : "Base",
    "DateTime" : "Base",
    "DHCP" :"Bhaskar",
    "Diagnostics" : "Base",
    "DNS" : "Base",
    "Fastpath": "Gulzar",
    "FIPS":"FIPS",
    "Firewall":"Gulzar",
    "Garner":"Kuvempu",
    "HA" : "Kabir",
    "HCL":"Base",
    "Heartbeat":"SyncSec",
    "HotFix":"QM",
    "HTTP-Proxy":"Web",
    "Import Export":"Base",
    "Infrastructure":"BLR",
    "Installation":"Base",
    "IPS":"IPS",
    "IPsec":"Krishna",
    "Licensing" : "Base",
    "LiveConnection":"Kuvempu",
    "Logging":"Kuvempu",
    "LogViewer" : "WAF",
    "Migration" : "Base",
    "Multilink":"Kabir",
    "Network":"Kabir",
    "OTP":"Kuvempu",
    "Perfomance":"Perfomance",
    "POP3-Proxy":"Nest",
    "PQA":"QM",
    "QM":"QM",
    "RED":"Vivaldi",    
    "RED_legacy":"Vivaldi",
    "RemoteAccessVPN":"RAVPN",
    "Reporting":"iView",
    "SDWAN":"Bhaskar",
    "Security":"Kabir",
    "SecurityPolicy":"Gulzar",
    "SEP":"",
    "SEP-CSC-Hybrid":"Picasso",
    "SF_CFR Compatability":"CM",
    "SMTP-Proxy":"Nest",
    "SNMP":"Karanth",
    "SophosConnectPolicy":"RAVPN",
    "SQL_Injection_UI":"Framework_UI",
    "SSLVPN":"Krishna",
    "SupportAccess":"Base",
    "SystemGraph":"Kabir",
    "TA-Framework":"TA-Framework",
    "Up2Date":"Base",
    "VPN":"Base",
    "WAF":"WAF",
    "Warhol":"Warhol",
    "WebInSnort":"Web",
    "WiFi":"Vivaldi",
    "Wizard":"Base",
    "Zone":"Verdi",
    "ZTNA":"ZTNA",   
}
