name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
    #get the name of changed manuscripts
      - name: Get changed manuscripts
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
         files: |
               *.manuscript
               
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

    #run python file
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
      - name: Print workspace directory
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          
      - name: Running Python file
        run: |
          import re
         
         # Specify the file path
         file_path = "${{ github.workspace }}/logs.txt"

          # Read the file content
          with open(file_path, 'r') as file:
            file_content = file.read()

          # Extract the "name" field key-value pair using a regular expression
          name = r"name\s*=>\s*'([^']*)'"
          name_match = re.search(name, file_content)

          category = r"category\s*=>\s*'([^']*)'"
          category_match = re.search(category, file_content)

          team = r"team\s*=>\s*'([^']*)'"
          team_match = re.search(team, file_content)

          if category_match:
            print(category_match.group(1).strip())
          else:
            print("No category field found in the file.")

          if name_match:
            print(name_match.group(1).strip())
          else:
            print("No name field found in the file.")

          if team_match:
            print(team_match.group(1).strip())
          else:
            print("No team field found in the file.")
  
      

          
          
      # - name: Run Python script
      #   run: |
      #     python fetch_file_name.py
