name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
    #get the name of changed manuscripts
      - name: Get changed manuscripts
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
         files: |
               *.manuscript
               
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

    #run python file
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
      - name: Print workspace directory
        run: |
          echo "Workspace directory: ${{ github.workspace }}"

      - name: Running Python file
        run: |
          import re

          # Specify the file path
          file_path = "/Users/yash.parmar/Documents/Perl/logs.txt"

         # Read the file content
         with open(file_path, 'r') as file:
         file_content = file.read()

         # Extract the "name" field key-value pair using a regular expression
         name  = r"name\s*=>\s*'([^']*)'"
         name = re.search(name, file_content)

         category = r"category\s*=>\s*'([^']*)'"
         category = re.search(category, file_content)

         team = r"team\s*=>\s*'([^']*)'"
         team = re.search(team, file_content)

         if category:
          print(category.group(1).strip())
         else:
          print("No  field found in the file.")


         if name:
          print(name.group(1).strip())
         else:
          print("No  field found in the file.")

         if team:
         print(team.group(1).strip())
         else:
          print("No  field found in the file.")
  
      

          
          
      # - name: Run Python script
      #   run: |
      #     python fetch_file_name.py
