on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List changed files in a specific directory
        env:
          SPECIFIC_DIR: path/to/specific/directory
          MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          echo "Modified files in $SPECIFIC_DIR:"
          for file in ${MODIFIED_FILES}; do
            if [[ "$file" == "$SPECIFIC_DIR"* ]]; then
              echo "$file"
            fi
          done

          echo "Added files in $SPECIFIC_DIR:"
          for file in ${ADDED_FILES}; do
            if [[ "$file" == "$SPECIFIC_DIR"* ]]; then
              echo "$file"
            fi
          done

          echo "Deleted files in $SPECIFIC_DIR:"
          for file in ${DELETED_FILES}; do
            if [[ "$file" == "$SPECIFIC_DIR"* ]]; then
              echo "$file"
            fi
          done
