name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
    #get the name of changed manuscripts
      - name: Get changed manuscripts
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
         files: |
               *.manuscript
               
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          
   
    #run python file

     #clone this repo
      - name: Checkout
        uses: actions/checkout@v4.1.6

      # Basic checkout
      # - name: Checkout basic
      #   uses: ./
      #   with:
      #     ref: test-data/v2/basic
      #     path: basic

      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         
      - name: Print workspace directory
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          
      - name: Fetch Root Files
        uses: actions/checkout@v4
        with:
         sparse-checkout: .     
    
      - name: Fetch Python File
        uses: actions/checkout@v4
        with :
          sparse-checkout: |
            fetch_file_name.py
          sparse-checkout-cone-mode: true

      # - name : Run Python File
      #   run : |
      #     python fetch_file_name.py

