name: Manual Trigger PR Workflow

on:
  workflow_dispatch:
    inputs:
      pull_request_branch:
        description: 'Pull Request Branch'
        required: true

jobs:

  test-changed-files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          *.manuscript
          
    - name: Test changed files
      run: |
        echo "Changed files:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        # Add your testing steps here
    
    - name: Current location with pwd
      run : |
          pwd 
    - name: Current location files
      run : |
          ls -la
