name: Manual Trigger Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        default: 'dev'

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Environment
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }} environment"
        # Add your deployment steps here
