name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: ./deploy.sh ${{ github.event.inputs.environment }}
        env:
          DEPLOY_ENV: ${{ github.event.inputs.environment }}
