name: Manual Trigger PR Workflow

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
      pull_request_branch:
        description: 'Pull Request Branch'
        required: true
      verison: 
        description: 'sw_version to run Testplan'
        required: true

jobs:

  test-changed-files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
      with:
         ref: refs/pull/${{ github.event.inputs.pull_request_number }}/head

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
       files: |
             *.manuscript

    - name: List all changed manuscripts
      env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
    - name: Current location with pwd
      run : |
          pwd 
    - name: Current location files
      run : |
          ls -la
    - name: Print Pull Request Branch
      run: |
        echo "The pull request branch is: ${{ github.event.inputs.pull_request_branch }}"
    - name: Print sw_verison
      run: |
        echo "The sw_verison is: ${{ github.event.inputs.verison }}"
