name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    runs-on:  ubuntu-latest #|| windows-latest || macos-latest
    name: Test changed-files
    permissions:
      pull-requests: write

    steps:
     #get the name of changed manuscripts
      - name: Get changed manuscripts
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
         files: |
               *.manuscript
      # Print the changed file in the console         
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Get Renamed .manuscript File
        env:
          FILES: ${{ toJson(github.event.pull_request.files) }}
        run: |
          files=($FILES)
          for ((i=0; i<${#files[@]}; i++)); do
            file="${files[$i]}"
            status=$(echo $file | jq -r '.status')
            filename=$(echo $file | jq -r '.filename')
            if [ "$status" == "renamed" ] && [[ "$filename" == *.manuscript ]]; then
              old_file=$(echo $file | jq -r '.previous_filename')
              new_file=$(echo $file | jq -r '.filename')
              echo "The .manuscript file '$old_file' was renamed to '$new_file'"
            fi
          done
          echo "Not found anything"

    
      #add comment in PR
      - name: Write comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
           Hi This Side Yash Parmar
    
      # - name: Print Files before checkout
      #   run : |
      #    ls -la
      # - name: Print working directory
      #   run : |
      #     echo ${{ github.workspace }}
     
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave:
    
     
            
      #clone this repo
      - name: Checkout
        uses: actions/checkout@v4.1.6

       #next two steps are for the print file in comment 
      - name: Read file contents
        id: read_file
        run: |
          contents=$(cat ${{ github.workspace }}/hello.txt)
          echo "contents<<table" >> $GITHUB_OUTPUT
          echo "| Field | Value |" >> $GITHUB_OUTPUT
          echo "| --- | --- |" >> $GITHUB_OUTPUT
          echo "| File Contents | $contents |" >> $GITHUB_OUTPUT
          echo "table" >> $GITHUB_OUTPUT

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        env:
          FILE_CONTENTS: ${{ steps.read_file.outputs.contents }}
        with:
          message: |
            First Comment
            ${{ steps.read_file.outputs.contents }}
      

         
      # setup for python
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests
         
      - name: Print workspace directory
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          
      - name: Current location with pwd
        run : |
          pwd   
          
      # - name: Fetch Root Files
      #   uses: actions/checkout@v4
      #   with:
      #    sparse-checkout: .     
    
     
      # Name of the manuscripts inside changed_files.txt
      - name: Write name of changed manuscripts
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt

      - name: Print changed_files.txt file
        run: | 
         cat changed_files.txt

        #next two steps are for the print file in comment 
      - name: Read file contents
        id: read_second_file
        run: |
          contents=$(cat ${{ github.workspace }}/changed_files.txt)
          echo "contents<<EOF" >> $GITHUB_OUTPUT
          echo "$contents" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        env:
         FILE_CONTENTS: ${{ steps.read_second_file.outputs.contents }}
        with:
          message: |
            Second Comment    
            ```
            ${{ env.FILE_CONTENTS }}
            ```
      # - name: Current location files
      #   run : |
      #     ls -la
         

      - name : Run Fetch File Name file
        run : |
          python fetch_file_name.py --input-file ${{ github.workspace }}/changed_files.txt

      - name: Current location files
        run : |
          ls -la

      # - name: Print dict file
      #   run : |
      #       cat output.pkl

      # - name : Run add testcase file
      #   run : |
      #    python add_testcase.py 
